server {
    # Nginx escucha en el puerto 80 dentro del contenedor
    listen 80;
    # Nombre del servidor
    server_name localhost;
    # Carpeta pública de Laravel
    root /var/www/html/public;
    # Archivos iniciales
    index index.php index.html;
    charset utf-8;

    # Cabeceras básicas de seguridad
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";

    # Rutas principales de Laravel
    location / {
        # Si el archivo existe, lo muestra y si no existe, manda la petición a index.php para que Laravel la gestione.
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Archivos estáticos: imágenes, CSS, JS, fuentes, etc.
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|woff|woff2|ttf|svg)$ {
    #le dice al navegador que puede guardar estos assets durante 1 año
        expires 1y;
        # Indica al navegador que puede guardar estos assets
        add_header Cache-Control "public, immutable";
        # Si el archivo no existe, devuelve error 404
        try_files $uri =404;
    }


    # Procesamiento de archivos PHP
    location ~ \.php$ {
        # Envía PHP al contenedor app, puerto 9000
        fastcgi_pass app:9000;
        # Archivo inicial PHP
        fastcgi_index index.php;
        # Ruta real del script PHP que se ejecutará
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        # Incluye parámetros FastCGI estándar
        include fastcgi_params;
        # Tiempo máximo de espera para scripts PHP largos
        fastcgi_read_timeout 300;
    }
    # Bloquea acceso a archivos ocultos como .env o .git
    location ~ /\.(?!well-known).* {
        deny all;
    }
    # Archivos de logs de Nginx
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}